DROP TABLE IF EXISTS libraries CASCADE;
CREATE TABLE "libraries" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  "lat" FLOAT NOT NULL,
  "long" FLOAT NOT NULL,
  "image_url" VARCHAR(512),
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);